version: '3.7'
services:
    nginx:
        image: 'nginx:latest'
        volumes:
            - {type: bind, source: ./nginx/nginx.conf, target: /etc/nginx/nginx.conf}
        ports:
            - {target: 80, published: 80, protocol: tcp}
        depends_on:
            - login
            - webapp
    webapp:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - {target: 3000, protocol: tcp}
    login:
        build:
            context: ./LoginNode
            dockerfile: Dockerfile
        ports:
            - {target: 8002, protocol: tcp}
        depends_on:
            - core
    core:
        build:
            context: ./CoreAPI
            dockerfile: Dockerfile
        ports:
            - {target: 8000, protocol: tcp}
        depends_on:
            - vehicle
            - citizen
            - mobile
            - associate
    vehicle:
        build:
            context: ./VehicleAPI
            dockerfile: Dockerfile
            args: 
                - PASSWORD=${PASSWORD}
        ports:
            - {target: 8004, protocol: tcp}
    citizen:
        build:
            context: ./CitizenAPI
            dockerfile: Dockerfile
            args: 
                - PASSWORD=${PASSWORD}
        ports:
            - {target: 8003, protocol: tcp}
    mobile:
        build:
            context: ./MobileAPI
            dockerfile: Dockerfile
            args: 
                - PASSWORD=${PASSWORD}
        ports:
            - {target: 8006, protocol: tcp}
    associate:
        build:
            context: ./AssociateAPI
            dockerfile: Dockerfile
            args: 
                - PASSWORD=${PASSWORD}
        ports:
            - {target: 8007, protocol: tcp}   
    finance:
        build:
            context: ./FinanceAPI
            dockerfile: Dockerfile
            args: 
                - PASSWORD=${PASSWORD}
        ports:
            - {target: 8005, protocol: tcp}   

