version: '3.7'
services:
    auditconsumer:
		image: rjharrisuk/auditconsumer
		depends on:
			- activemq
        build:
			context: ./AuditConsumer
            dockerfile: Dockerfile
        ports:
            - {target: 8008, published: 8008, protocol: tcp}
    activemq:
        image: rmohr/activemq
        ports:
            - {target: 8161, published: 8161, protocol: tcp}
	mongo:
		image: mongo
		ports:
			- {target: 27001, published: 27001, protocol: tcp}